### ISSUE TITLE
[TRACKING] Missing and wanted commands

### ISSUE THREAD

**Issue by benw202** [flybywiresim/discord-bot#8]
This is a list of missing and wanted commands for the bot. Please comment with any commands you wish to see added.

- [ ] ADIRS (https://github.com/flybywiresim/discord-bot/pull/7)
- [ ] Installer errors (https://github.com/flybywiresim/discord-bot/pull/7)
- [ ] Reported issues (https://github.com/flybywiresim/discord-bot/pull/7)
- [ ] Autopilot (https://github.com/flybywiresim/discord-bot/pull/7)
- [ ] Checklist

**Comment by Valastiri** [comment]
Currently inop

- mute command
- whois command

**Comment by benw202** [comment]
@Valastiri Thanks, checklist has been added to #7, I will add mute in. 

Can you describe whois? Do you have an example of it from before?

**Comment by frankkopp** [comment]
.versions ==> link to https://docs.flybywiresim.com/start/fbw-versions/

**Comment by NUTTTTTTTT** [comment]
Requested on Discord - .beginnerguide or similar to refer to the docs guide.

**Comment by frankkopp** [comment]
Request: .fdr 

```
Is it possible that you send us some some files:
https://docs.flybywiresim.com/fbw-a32nx/feature-guides/autopilot-fbw/#work-folder-location

Check in your work folder for fdr files (flight data recorder) for the flight you did. You should recognize the correct one by the filename which is the date of the flight. For a long flight it might been split into several files.

Compress/Zip it and upload it to a sharing site (e.g. https://www.swisstransfer.com/) as these files are likely to be too large for Discord .

This file will allow us to see some more details to understand what happened.
```

Doesn't have to be exactly this but needs to provide the info.

**Comment by frankkopp** [comment]
.discontinuity / .disco

https://docs.flybywiresim.com/pilots-corner/beginner-guide/preparing-mcdu/#discontinuity

**Comment by NathanInnes** [comment]
Sticky still a feature we need? Don't really see the need in it anymore.
